import { useEffect,useRef,useState } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js'
import type { Layer } from './noiseEngine'
import { BIOMES,BIOME_COLORS,biomeAt,climateAt,heightAt,tideAt,velocityAt,reefSuitable,seedEcology,stepEcology,findPath,hash,random,clamp } from './worldSystems'
import { buildTree,leafTexture,terrainMaterial,coastalWater,disposeScene } from './natureRendering'
import { FieldCard,FieldRange } from './FieldControls'
import './FieldStudies.css'

const defaults={temperature:.75,moisture:.63,relief:1,resolution:160,season:.7,tide:1.4,period:24,current:2,wind:1.5,direction:25,swirl:1,growth:1,reproduction:1,dispersal:8,competition:5,iterations:2,angle:30,density:.75,pathCost:12,reef:1,fog:.003}
type Settings=typeof defaults
type View='Landscape'|'Biomes'|'Moisture'|'Temperature'
export default function LivingWorld({layers,solo,active}:{layers:Layer[];solo:number|null;active:boolean}){
 const [s,setS]=useState(defaults),[running,setRunning]=useState(false),[view,setView]=useState<View>('Landscape'),[vectors,setVectors]=useState(true),[skeleton,setSkeleton]=useState(false),[specimen,setSpecimen]=useState(false),[wire,setWire]=useState(false),[reset,setReset]=useState(0)
 const [hud,setHud]=useState({time:0,trees:0,births:0,deaths:0,sea:0,coral:0,exposed:0,route:0,triangles:0,fps:0})
 const mount=useRef<HTMLDivElement>(null),plot=useRef<HTMLCanvasElement>(null),cmd=useRef<{camera:(v:string)=>void;step:(seconds?:number)=>void;save:()=>void}|null>(null)
 const live=useRef({s,running,view,vectors,wire,active,skeleton,specimen});useEffect(()=>{live.current={s,running,view,vectors,wire,active,skeleton,specimen}},[s,running,view,vectors,wire,active,skeleton,specimen])
 const set=(k:keyof Settings,v:number)=>setS(p=>({...p,[k]:v}))
 useEffect(()=>{
  const el=mount.current;if(!el)return
  const scene=new THREE.Scene();scene.background=new THREE.Color('#e8dcd2');scene.fog=new THREE.FogExp2('#e8dcd2',.003)
  const camera=new THREE.PerspectiveCamera(43,1,.1,700);camera.position.set(105,92,123)
  const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement)
  renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Living coast. Drag to orbit; F toggles wireframe; Space pauses.');const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5,0);controls.enableDamping=true;controls.maxDistance=260;controls.maxPolarAngle=Math.PI*.49
  scene.add(new THREE.HemisphereLight('#f3dfbd','#68777f',1.7));const sun=new THREE.DirectionalLight('#ffe2b4',2.5);sun.position.set(-50,90,35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;sun.shadow.camera.far=240;sun.shadow.normalBias=.15;scene.add(sun)
  const height=(x:number,z:number)=>heightAt(layers,solo,x,z,s.relief)
  const habitat=(x:number,z:number)=>{const h=height(x,z),slope=Math.hypot(height(x+.5,z)-height(x-.5,z),height(x,z+.5)-height(x,z-.5));return {height:h,slope,...climateAt(x,z,h,{temperature:s.temperature,moisture:s.moisture})}}
  const terrainGeo=new THREE.PlaneGeometry(160,160,s.resolution,s.resolution);terrainGeo.rotateX(-Math.PI/2)
  const pos=terrainGeo.getAttribute('position'),colors=new Float32Array(pos.count*3),habitats=Array.from({length:pos.count},(_,i)=>habitat(pos.getX(i),pos.getZ(i)))
  for(let i=0;i<pos.count;i++)pos.setY(i,habitats[i].height)
  terrainGeo.setAttribute('color',new THREE.BufferAttribute(colors,3));terrainGeo.computeVertexNormals();const diagnosticMat=new THREE.MeshBasicMaterial({vertexColors:true}),terrainMat=terrainMaterial(),ground=new THREE.Mesh<THREE.BufferGeometry,THREE.Material>(terrainGeo,terrainMat);ground.receiveShadow=true;scene.add(ground)
  const mapSize=161,texels=new Uint8Array(mapSize*mapSize*4)
  for(let z=0;z<mapSize;z++)for(let x=0;x<mapSize;x++)texels.set([Math.round(clamp((height(x-80,z-80)+24)/64)*255),0,0,255],(z*mapSize+x)*4)
  const groundMap=new THREE.DataTexture(texels,mapSize,mapSize);groundMap.minFilter=groundMap.magFilter=THREE.LinearFilter;groundMap.needsUpdate=true
  const waterMat=coastalWater(groundMap),water=new THREE.Mesh(new THREE.PlaneGeometry(160,160,100,100),waterMat);water.rotation.x=-Math.PI/2;scene.add(water)
  const ecology=seedEcology(habitat,17,s.density),tree=buildTree(s.iterations,s.angle),leaves=leafTexture()
  function frameSpecimen(){const p=ecology.plants[0];if(!p)return;tree.branches.computeBoundingBox();const y=height(p.x,p.z),h=(tree.branches.boundingBox!.max.y+1)*p.size*(p.species?2.1:2.6);camera.position.set(p.x+h*1.1,y+h*.65,p.z+h*1.5);controls.target.set(p.x,y+h*.5,p.z)}
  if(live.current.specimen)frameSpecimen()
  const trunkMat=new THREE.MeshStandardMaterial({color:'#554652',roughness:1}),leafMat=new THREE.MeshStandardMaterial({map:leaves,alphaTest:.48,side:THREE.DoubleSide,roughness:1,vertexColors:false})
  const windUniform={value:0},windStrength={value:1}
  leafMat.onBeforeCompile=shader=>{shader.uniforms.windTime=windUniform;shader.uniforms.windStrength=windStrength;shader.vertexShader='uniform float windTime,windStrength;\n'+shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x+=sin(windTime*1.6+position.y+position.x)*.035*position.y*windStrength;')}
  const trunks=new THREE.InstancedMesh(tree.branches,trunkMat,300),crowns=new THREE.InstancedMesh(tree.foliage,leafMat,300);trunks.castShadow=true;crowns.castShadow=true;trunks.frustumCulled=crowns.frustumCulled=false;scene.add(trunks,crowns)
  const rng=random(418),dummy=new THREE.Object3D(),color=new THREE.Color()
  const grassPieces:THREE.BufferGeometry[]=[]
  for(let k=0;k<3;k++){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([-.16,0,0,.16,0,0,.14,1.1,0, .14,1.1,0,.16,0,0,.28,.6,0],3));g.computeVertexNormals();g.rotateY(k*Math.PI/3);grassPieces.push(g)}
  const grassGeo=mergeGeometries(grassPieces);grassPieces.forEach(g=>g.dispose());const grass=new THREE.InstancedMesh(grassGeo,new THREE.MeshStandardMaterial({color:'#b7ad68',side:THREE.DoubleSide,roughness:1}),2400)
  const stones=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:'#aba4a2',roughness:1}),130)
  let grassCount=0,rockCount=0
  for(let i=0;i<4500;i++){const x=(rng()-.5)*140,z=(rng()-.5)*140,c=habitat(x,z);if(c.height<2||c.slope>1)continue
   if(grassCount<2400&&c.height<24){dummy.position.set(x,c.height,z);dummy.rotation.set(0,rng()*6.28,(rng()-.5)*.3);dummy.scale.setScalar(.5+rng());dummy.updateMatrix();grass.setMatrixAt(grassCount++,dummy.matrix)}
   if(i%23===0&&rockCount<130){dummy.position.set(x,c.height-.15,z);dummy.scale.set(1+rng()*1.7,.5+rng(),.7+rng());dummy.rotation.set(rng(),rng()*6,0);dummy.updateMatrix();stones.setMatrixAt(rockCount++,dummy.matrix)}
  }grass.count=grassCount;stones.count=rockCount;grass.receiveShadow=true;stones.castShadow=stones.receiveShadow=true;scene.add(grass,stones)
  const reefGeo=buildTree(1,43),reefMat=new THREE.MeshStandardMaterial({color:'#dd977f',roughness:.8}),corals=new THREE.InstancedMesh(reefGeo.branches,reefMat,500);corals.frustumCulled=false;scene.add(corals);reefGeo.foliage.dispose()
  const reefSites=Array.from({length:900},()=>({x:(rng()-.5)*150,z:(rng()-.5)*150})).map(p=>({...p,...habitat(p.x,p.z)}))
  const pointsCount=360,particlePos=new Float32Array(pointsCount*3),particleGeo=new THREE.BufferGeometry();particleGeo.setAttribute('position',new THREE.BufferAttribute(particlePos,3));const particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({color:'#fff5d5',size:.48,transparent:true,opacity:.85}));scene.add(particles)
  for(let i=0;i<pointsCount;i++){particlePos[i*3]=(rng()-.5)*150;particlePos[i*3+2]=(rng()-.5)*150}
  const arrows:THREE.ArrowHelper[]=[];for(let z=-64;z<=64;z+=16)for(let x=-64;x<=64;x+=16){const a=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(x,0,z),3,'#fff3c7',1,.5);arrows.push(a);scene.add(a)}
  const routeGroup=new THREE.Group();scene.add(routeGroup);let routeLength=0,lastRouteSea=Infinity,lastPathCost=-1
  function route(sea:number){routeGroup.children.forEach(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});routeGroup.clear();const n=41,hs=new Float32Array(n*n);for(let z=0;z<n;z++)for(let x=0;x<n;x++)hs[z*n+x]=height(x*4-80,z*4-80)
   const indices=findPath(hs,n,4,25*n+13,14*n+25,sea,live.current.s.pathCost),positions:number[]=[];routeLength=0
   for(let i=1;i<indices.length;i++){const a=indices[i-1],b=indices[i],ax=a%n*4-80,az=Math.floor(a/n)*4-80,bx=b%n*4-80,bz=Math.floor(b/n)*4-80,len=Math.hypot(bx-ax,bz-az),dx=-(bz-az)/len*.85,dz=(bx-ax)/len*.85;routeLength+=len
    const verts=[[ax+dx,az+dz],[ax-dx,az-dz],[bx+dx,bz+dz],[bx-dx,bz-dz]];for(const j of [0,1,2,2,1,3])positions.push(verts[j][0],height(...verts[j] as [number,number])+.15,verts[j][1])}
   const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.computeVertexNormals();routeGroup.add(new THREE.Mesh(geo,pathMat));lastRouteSea=sea;lastPathCost=live.current.s.pathCost
  }
  const pathMat=new THREE.MeshStandardMaterial({color:'#eac291',side:THREE.DoubleSide,roughness:1});route(0)
  let lastTrees=-1,lastSeason=-1,lastReefSea=Infinity,lastReefDensity=-1;let time=0,accumulator=0,last=performance.now(),frame=0,lastHud=0,lastColor='',reefCount=0,frames=0,frameStart=last,rate=0
  const history:number[]=[ecology.plants.length]
  function tick(){time+=1/30;const cfg=live.current.s,sea=tideAt(time,cfg.tide,cfg.period);if(Math.round(time*30)%15===0){stepEcology(ecology,habitat,.5,sea,cfg.growth,cfg.reproduction,cfg.dispersal,cfg.competition);history.push(ecology.plants.length);if(history.length>180)history.shift()}
   for(let i=0;i<pointsCount;i++){const k=i*3,v=velocityAt(particlePos[k],particlePos[k+2],time,cfg.current,cfg.direction,cfg.swirl);particlePos[k]+=v[0]/30;particlePos[k+2]+=v[1]/30;for(const axis of [k,k+2]){if(particlePos[axis]>79)particlePos[axis]=-79;if(particlePos[axis]<-79)particlePos[axis]=79}}
  }
  cmd.current={step(seconds=1){for(let i=0;i<30*seconds;i++)tick()},camera(mode){setSpecimen(mode==='Tree specimen');if(mode==='Tree specimen'){setRunning(false);frameSpecimen()}else if(mode==='Forest walk'){camera.position.set(8,20,42);controls.target.set(-3,10,0)}else if(mode==='Reef overlook'){camera.position.set(67,17,50);controls.target.set(45,0,25)}else{camera.position.set(105,92,123);controls.target.set(0,5,0)}controls.update()},save(){const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download=`living-coast-${time.toFixed(1)}s.png`;a.click()}}
  const keys=(e:KeyboardEvent)=>{if(!live.current.active||e.target instanceof HTMLElement&&e.target.closest('input,button,select,textarea,[contenteditable]'))return;if(e.key===' '){e.preventDefault();setRunning(v=>!v)}if(e.key.toLowerCase()==='f')setWire(v=>!v)};window.addEventListener('keydown',keys)
  const ro=new ResizeObserver(()=>{if(el.clientWidth&&el.clientHeight){renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}});ro.observe(el)
  function animate(now:number){frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.1);last=now;if(!live.current.active||document.hidden)return
   const cfg=live.current.s;if(live.current.running){accumulator+=dt;while(accumulator>=1/30){tick();accumulator-=1/30}}
   const sea=tideAt(time,cfg.tide,cfg.period),key=[live.current.view,cfg.season,Math.round(sea*2)].join(':')
   if(key!==lastColor){for(let i=0;i<pos.count;i++){const c=habitats[i],biome=biomeAt(c.height,c.slope,sea,c);color.set(BIOME_COLORS[biome]);if(live.current.view==='Moisture')color.set('#e5c48b').lerp(new THREE.Color('#397e8d'),c.moisture);else if(live.current.view==='Temperature')color.set('#6e93b8').lerp(new THREE.Color('#e98a62'),c.temperature);else if(live.current.view==='Landscape'&&biome===4)color.lerp(new THREE.Color('#bcab74'),cfg.season*.48);color.toArray(colors,i*3)}terrainGeo.getAttribute('color').needsUpdate=true;lastColor=key}
   terrainMat.wireframe=diagnosticMat.wireframe=live.current.wire;ground.material=live.current.view==='Landscape'?terrainMat:diagnosticMat;ground.visible=!live.current.specimen;water.visible=live.current.view==='Landscape'&&!live.current.wire&&!live.current.specimen;grass.visible=stones.visible=trunks.visible=crowns.visible=live.current.view==='Landscape'&&!live.current.wire
   ;(scene.fog as THREE.FogExp2).density=cfg.fog
   water.position.y=sea;waterMat.uniforms.time.value=time;waterMat.uniforms.level.value=sea;waterMat.uniforms.speed.value=cfg.current;waterMat.uniforms.direction.value=cfg.direction*Math.PI/180;waterMat.uniforms.swirl.value=cfg.swirl
   windUniform.value=time;windStrength.value=cfg.wind
   if(lastTrees!==ecology.time||lastSeason!==cfg.season){
   trunks.count=crowns.count=ecology.plants.length
   ecology.plants.forEach((p,i)=>{dummy.position.set(p.x,height(p.x,p.z),p.z);dummy.rotation.set(0,hash(p.id,4)*6.28,0);dummy.scale.setScalar(p.size*(p.species?2.1:2.6));dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);crowns.setMatrixAt(i,dummy.matrix);color.set(p.species?'#94a161':'#6f9266').lerp(new THREE.Color(p.species?'#ffd265':'#f5a13b'),cfg.season).multiplyScalar(.7+p.health*.3);crowns.setColorAt(i,color)})
   trunks.instanceMatrix.needsUpdate=crowns.instanceMatrix.needsUpdate=true;if(crowns.instanceColor)crowns.instanceColor.needsUpdate=true
   renderer.shadowMap.needsUpdate=true;lastTrees=ecology.time;lastSeason=cfg.season}
   if(Math.abs(sea-lastReefSea)>.04||lastReefDensity!==cfg.reef){reefCount=0;for(let i=0;i<reefSites.length&&reefCount<500;i++){const p=reefSites[i];if(hash(i,2)>cfg.reef||!reefSuitable(-p.height,p.temperature,p.slope))continue;dummy.position.set(p.x,p.height,p.z);dummy.rotation.set(0,hash(i,4)*6,0);dummy.scale.setScalar(.4+hash(i,3)*.55);dummy.updateMatrix();corals.setMatrixAt(reefCount++,dummy.matrix)}corals.count=reefCount;corals.instanceMatrix.needsUpdate=true;lastReefSea=sea;lastReefDensity=cfg.reef}corals.visible=live.current.view==='Landscape'&&!live.current.specimen
   for(let i=0;i<pointsCount;i++){const k=i*3;particlePos[k+1]=height(particlePos[k],particlePos[k+2])<sea?sea+.22:-30}particleGeo.getAttribute('position').needsUpdate=true;particles.visible=live.current.vectors&&live.current.view==='Landscape'&&!live.current.specimen
   for(const a of arrows){const v=velocityAt(a.position.x,a.position.z,time,cfg.current,cfg.direction,cfg.swirl),length=Math.hypot(...v);a.position.y=sea+.5;a.visible=live.current.vectors&&!live.current.specimen&&live.current.view==='Landscape'&&height(a.position.x,a.position.z)<sea&&length>.01;a.setDirection(new THREE.Vector3(v[0],0,v[1]).normalize());a.setLength(Math.max(.1,length*1.4),.7,.4)}
   if(Math.abs(sea-lastRouteSea)>.5||cfg.pathCost!==lastPathCost)route(sea)
   routeGroup.visible=live.current.view==='Landscape'&&!live.current.specimen;crowns.visible=crowns.visible&&!live.current.skeleton;trunks.count=crowns.count=live.current.specimen?Math.min(1,ecology.plants.length):ecology.plants.length;if(live.current.specimen)grass.visible=stones.visible=false;controls.update();renderer.render(scene,camera);frames++
   if(now-frameStart>1000){rate=frames*1000/(now-frameStart);frames=0;frameStart=now}
   if(now-lastHud>500){setHud({time,trees:ecology.plants.length,births:ecology.births,deaths:ecology.deaths,sea,coral:reefCount,exposed:reefSites.filter((p,i)=>hash(i,2)<=cfg.reef&&reefSuitable(-p.height,p.temperature,p.slope)&&sea<p.height+1.2).length,route:routeLength,triangles:renderer.info.render.triangles,fps:rate});lastHud=now
    const canvas=plot.current,c=canvas?.getContext('2d');if(c&&canvas){canvas.width=280;canvas.height=110;c.fillStyle='#f2f1e6';c.fillRect(0,0,280,110);c.strokeStyle='#718957';c.beginPath();history.forEach((v,i)=>{const x=i/179*280,y=100-v/300*90;if(i)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke();c.fillStyle='#53624b';c.font='10px sans-serif';c.fillText('Population / 0–300 plants',8,13)}
   }
  }frame=requestAnimationFrame(animate)
  return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();window.removeEventListener('keydown',keys);leaves.dispose();groundMap.dispose();sun.shadow.dispose();disposeScene(scene);diagnosticMat.dispose();terrainMat.dispose();pathMat.dispose();renderer.dispose();el.removeChild(renderer.domElement);cmd.current=null}
 },[layers,solo,s.resolution,s.relief,s.temperature,s.moisture,s.iterations,s.angle,s.density,reset])
 return <main className="field-study"><header className="sim-header"><div><span className="sim-eyebrow">SESSIONS 3 · 4 · 6 · 7 / CONNECTED SYSTEMS</span><h1>The living coast.</h1><p>Follow a trail from the forest to the tide pools. Watch the world respond.</p></div><div className="sim-status"><span>{running&&active?'Running':'Paused'}</span><strong>{hud.time.toFixed(1)}</strong><span>model seconds</span></div></header>
 <div className="field-layout"><section className="field-scene"><div className="field-toolbar">{['Overview','Forest walk','Reef overlook','Tree specimen'].map(v=><button key={v} onClick={()=>cmd.current?.camera(v)}>{v}</button>)}<button onClick={()=>cmd.current?.save()}>Save frame</button></div><div className="field-canvas" ref={mount}/><div className="field-legend">{view==='Moisture'?<span>Moisture: ochre = 0 (dry) → teal = 1 (wet)</span>:view==='Temperature'?<span>Temperature: blue = 0 (cold) → coral = 1 (warm)</span>:BIOMES.map((b,i)=><span key={b}><i style={{background:BIOME_COLORS[i]}}/>{b}</span>)}</div><div className="field-toolbar">{(['Landscape','Biomes','Moisture','Temperature'] as View[]).map(v=><button aria-pressed={view===v} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><div className="field-stats"><span><strong>{hud.trees}</strong>living trees</span><span><strong>+{hud.births} / −{hud.deaths}</strong>births / deaths</span><span><strong>{hud.sea.toFixed(2)} u</strong>tide level</span><span><strong>{hud.coral}</strong>reef colonies · {hud.exposed} exposed tips</span><span><strong>{hud.route.toFixed(0)} u</strong>walkable trail</span></div><div className="field-toolbar"><button className="sim-primary" onClick={()=>setRunning(v=>!v)}>{running?'Pause':'Start world'}</button><button onClick={()=>{setRunning(false);cmd.current?.step()}}>+1 second</button><button onClick={()=>{setRunning(false);cmd.current?.step(10)}}>+10 seconds</button><button onClick={()=>{setRunning(false);setReset(v=>v+1)}}>Reset world</button><label><input type="checkbox" checked={vectors} onChange={e=>setVectors(e.target.checked)}/>Current arrows</label><label><input type="checkbox" checked={wire} onChange={e=>setWire(e.target.checked)}/>Wireframe</label></div><div className="field-caption">Climate drives biomes; tides expose reefs; A* trails avoid flooded cells. Seeded L-system trees grow, compete and disperse seeds. These are bounded educational models, not a forecast. {Math.round(hud.fps)} rendered fps · {hud.triangles.toLocaleString()} triangles.</div></section>
 <aside className="field-inspector"><FieldCard title="A changing shoreline"><FieldRange label="Tide amplitude" value={s.tide} min={0} max={4} onChange={v=>set('tide',v)} unit=" u"/><FieldRange label="Tide period" value={s.period} min={8} max={60} step={1} onChange={v=>set('period',v)} unit=" s"/><FieldRange label="Current speed" value={s.current} min={0} max={5} onChange={v=>set('current',v)} unit=" u/s"/><FieldRange label="Flow direction" value={s.direction} min={0} max={360} step={5} onChange={v=>set('direction',v)} unit="°"/><FieldRange label="Eddy strength" value={s.swirl} min={0} max={3} onChange={v=>set('swirl',v)}/><FieldRange label="Reef density" value={s.reef} min={0} max={1} onChange={v=>set('reef',v)}/><p>Coral is seeded at warm, gentle seabed sites 0.4–6 u below mean sea level. The same colonies become exposed or submerged as the sinusoidal tide changes; currents are a prescribed vector field. Use Fluid laboratory for pressure projection.</p></FieldCard>
 <FieldCard title="Climate & biomes"><FieldRange label="Temperature" value={s.temperature} min={.2} max={1} onChange={v=>set('temperature',v)}/><FieldRange label="Moisture" value={s.moisture} min={0} max={1} onChange={v=>set('moisture',v)}/><FieldRange label="Relief" value={s.relief} min={.3} max={2} onChange={v=>set('relief',v)}/><label>Terrain resolution<select value={s.resolution} onChange={e=>set('resolution',+e.target.value)}>{[96,160,224].map(v=><option key={v} value={v}>{v} × {v}</option>)}</select></label><p>Climate, relief and resolution regenerate this world. Moisture and temperature views show normalized values 0–1. The shared Noise laboratory stack supplies terrain detail.</p></FieldCard>
 <FieldCard title="A forest with a history"><FieldRange label="Growth rate" value={s.growth} min={0} max={3} onChange={v=>set('growth',v)}/><FieldRange label="Reproduction rate" value={s.reproduction} min={0} max={3} onChange={v=>set('reproduction',v)}/><FieldRange label="Seed dispersal" value={s.dispersal} min={2} max={18} step={1} onChange={v=>set('dispersal',v)} unit=" u"/><FieldRange label="Competition radius" value={s.competition} min={2} max={10} onChange={v=>set('competition',v)} unit=" u"/><canvas ref={plot} className="field-plot" aria-label="Population history from zero to 300 plants"/><p>Persistent age, size and health; crowding slows growth, flooding lowers health. 300 is a performance cap. The plot records this run.</p></FieldCard>
 <FieldCard title="Branching & atmosphere"><label><input type="checkbox" checked={skeleton} onChange={e=>setSkeleton(e.target.checked)}/>Branch skeleton</label><p>{5**s.iterations} segments per tree. Use Tree specimen to inspect one individual.</p><FieldRange label="L-system iterations" value={s.iterations} min={1} max={3} step={1} onChange={v=>set('iterations',v)}/><FieldRange label="Branch angle" value={s.angle} min={15} max={50} step={1} onChange={v=>set('angle',v)} unit="°"/><FieldRange label="Initial tree density" value={s.density} min={.1} max={1} onChange={v=>set('density',v)}/><FieldRange label="Autumn palette" value={s.season} min={0} max={1} onChange={v=>set('season',v)}/><FieldRange label="Wind strength" value={s.wind} min={0} max={4} onChange={v=>set('wind',v)}/><FieldRange label="Atmospheric haze" value={s.fog} min={0} max={.02} step={.001} onChange={v=>set('fog',v)}/><FieldRange label="Trail slope penalty" value={s.pathCost} min={0} max={40} step={1} onChange={v=>set('pathCost',v)}/><p>Grammar: F → F[+F]F[-F][&F]. Branching and initial-density changes reset the population. Autumn color and haze are appearance controls.</p></FieldCard></aside></div><footer>{hud.route===0?'Trail flooded or disconnected. Lower the tide or change the terrain. ':''}The original erosion experiment remains in Simulation map. This coast has its own clock; hidden studies pause automatically.</footer></main>
}
